export const GET_STATUSES_SUCCESS = "GET_STATUSES_SUCCESS";
export const GET_STATUSES_FAILED = "GET_STATUSES_FAILED";

export const POST_STATUS_SUCCESS = "POST_STATUS_SUCCESS";
export const POST_STATUS_FAILED = "POST_STATUS_FAILED";

export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS";
export const DELETE_STATUS_FAILED = "DELETE_STATUS_FAILED";
