export const GET_CONVOS_SUCCESS = "GET_CONVOS_SUCCESS";
export const GET_CONVOS_FAILED = "GET_CONVOS_FAILED";

export const SEND_CONVO_SUCCESS = "SEND_CONVO_SUCCESS";
export const SEND_CONVO_FAILED = "SEND_CONVO_FAILED";
